# Generated by Django 3.2.7 on 2021-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
